### ISSUE TITLE
Draw schematics and connection prototyping

### ISSUE THREAD

**Issue by srikanthpendem** [srikanthpendem/capstoneproject#10]

**Comment by Devanggajjar** [comment]
Collected the UART  pin information for all the components for doing the connection. Components include

1.) Beagle Bone Black.
2.) Finger Print Module GT 521F32
3.) GPS Module
4.) Wifi Module

**Comment by Devanggajjar** [comment]
Today I did the Interfacing of the FPS module with the BBB. The FPS module we are using is GT521F32. The pin connections are as follows.

**_FPS with BBB:_**

1. Tx –  UART 4_Rx_GPIO_30 Pin--> 11
2.  Rx – UART 4_Tx_GPIO_31 Pin--> 13
3. Vin – (VDD +5VP) Pin--> 5
4. GND – DGND Pin-->1
![Schematic_Fingerprint sensor schematics_2020-07-14_22-22-26](https://user-images.githubusercontent.com/55203414/87496134-fd59df00-c620-11ea-8fbe-9c5dc672ac8b.png)

**Comment by Devanggajjar** [comment]
The interfacing of the GPS and BBB are as below

**_GPS with BBB:_**

1. Rx –  UART 4_Rx_GPIO_30 Pin--> 24 
2. Tx – UART 4_Tx_GPIO_31 Pin-->  26
3. Vin – (VDD +5VP) Pin--> 6
4. GND – DGND Pin--> 2

*************************************************************************************************************************************
*************************************************************************************************************************************
![Screenshot from 2020-07-16 23-04-41](https://user-images.githubusercontent.com/55203414/87744430-7c821b00-c7b9-11ea-8af2-3a76ea419a0d.png)

**Comment by Devanggajjar** [comment]
The interfacing of the Buttons and BBB needs the pull-down resistor of 1kOhm or above is mandatory.

**_Buttons with BBB:_**

1. GND

2. VCC

3. Pin 22

 4  Pin 21
 
*********************************************************************************************************************************
*********************************************************************************************************************************

![Button Interface](https://user-images.githubusercontent.com/55203414/87843369-11504b80-c882-11ea-9cf8-a76c2f6f16fe.png)

**Comment by mikeshams** [comment]
1. What issues did you or others might face working with EasyEDA and how to solve them?

**Comment by Devanggajjar** [comment]
Sometimes we don't find the required components, in that case, we might need to make our own component by looking at the datasheet and components dimensions. which is way difficult for a Beginners.
