### ISSUE TITLE
Interface GPS to Beaglebne

### ISSUE THREAD

**Issue by srikanthpendem** [srikanthpendem/capstoneproject#11]
- [x] Read the data from GPS.
- [x] C code to read data from GPS.
- [x] Filter only a single string from NMEA.
- [x] Parse the string filtered.
- [x] Show the output.
- [x] Upload it to the cloud.

**Comment by srikanthpendem** [comment]
Tested UART Reception and Transmission.

**Comment by srikanthpendem** [comment]
**uartread.c** has been tested with GPS and the code works perfectly.  
Perfect GPS coordinates have also read.

**Comment by srikanthpendem** [comment]
Parsing NMEA Strings are partially done.

**Comment by srikanthpendem** [comment]
Successfully filtered
![gpgga](https://user-images.githubusercontent.com/55446776/88354772-0d17a880-cd30-11ea-993e-0377c85992ee.png)
 the GPGGA String from NMEA Sentences.

**Comment by srikanthpendem** [comment]
**GPS Data is totally parsed and working perfectly.**     

![Capture](https://user-images.githubusercontent.com/55446776/88958962-388a1e00-d26f-11ea-8e78-fc172d976f85.PNG)

**Comment by srikanthpendem** [comment]
**Everything is set. This is the final version of the source code**
![Capture](https://user-images.githubusercontent.com/55446776/89089568-f561a500-d36b-11ea-869f-054b46170e00.PNG)

**Comment by srikanthpendem** [comment]
**The website has been designed and successfully uploaded the GPS logs.**
![image](https://user-images.githubusercontent.com/55446776/89132269-fff17b00-d4e0-11ea-8716-bb8a2ea5656d.png)

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of a GPS to the BBB in terms of Hardware and software?
2. How do you solve them?

**Comment by srikanthpendem** [comment]
1. GPS device doesn't work properly indoors, use an antenna.
2. Please use any advanced IDE to compile and debug the program.
3. Installing the compiler might be challenging. But it is possible!
3. Make sure the connections are proper. soldering the component is the best option to avoid communication errors.
