### ISSUE TITLE
Setup the Cloud Server

### ISSUE THREAD

**Issue by srikanthpendem** [srikanthpendem/capstoneproject#12]

**Comment by loveuppal** [comment]
It is all related to the aws account. AWS stands for amazon web services. In addition to this cloud computing which can be done with two modes which are GUI and CLI. These commands will help uploading the objects. The first mode is simple and just can be done with uploading but second mode is not that simple. We need commands to upload and most importantly access key should be generated. Using this key we can configure AWS and use it .

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connecting the BBB to the AWS?
2. What's the limitation of free trial usage of AWS?
3. What are the pros and cons of going with AWS vs. ThingSpeak in the context of cloud services?

**Comment by mikeshams** [comment]
4. Did you use DynamoDB in your project? Why?

**Comment by srikanthpendem** [comment]
1. Installing the AWS in the ARM compiler might give a problem, there were no official installing instructions on their website. We have to find the install setups from other sources from the internet.
2. Limited Technical Support, Limited Storage in the Free trial.
3. Thingspeak is good for small home projects or students projects etc, whilst AWS has much advanced technical support with many features. AWS is used in bigger commercial and potential projects. 
4. We actually do not need a database for our small project. We just need a **storage** **bucket** to upload our data, save and retrieve whenever needed.

**Comment by loveuppal** [comment]
1.Installing the AWS in the ARM compiler might give a problem, there were no official installing instructions on their website. We have to find the install setups from other sources from the internet.
2. Limited Technical Support, Limited Storage in the Free trial.
3. Thingspeak is good for small home projects or students projects etc, whilst AWS has much advanced technical support with many features. AWS is used in bigger commercial and potential projects.
4. We actually do not need a database for our small project. We just need a storage bucket to upload our data, save and retrieve whenever needed.

**Comment by mikeshams** [comment]
5. How a

is any changes in around your project via FPS, Keypad, etc reflected on the web?

**Comment by loveuppal** [comment]
The location history of web page is dynamic always i.e every GPS access will be upgraded to the site accordingly.
The key accesses we web page will show access done through keypad.
The bio metric access web page will show the history of access done through keypad.
The bio metric access web page will show the history of access done through fingerprint sensor.

**Comment by loveuppal** [comment]
if any changes or any kind of modification is done through either finger print scanner(FPS), keypad, these changes will be reflected on the web page with the help of **c code**  automatically. the message  "key has been accessed" will be shown on the web page. In addition the time and date on which the change was added will also be shown.
