### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by mikeshams** [srikanthpendem/capstoneproject#5]

**Comment by loveuppal** [comment]
- [ ] Beaglebone
 - Why Beaglebone:
   - It is the heart of the whole project working as
microcontroller and controls all peripherals being used
- [ ] GPS LLC 746
 - Why GPS LLC 746:
   - This component will track or locate the
coordinates where the authenticator is encrypting or
decrypting the data.
- [ ] GT-521F32
 - Why GT-521F32:
   - This component will read and identify
the finger impression in the project.
- [ ] Wi-Fi AC600 USB2.0
 - Why Wi-Fi AC600 USB2.0:
   - It helps to connect the project with
internet or sends the information to cloud
- [ ] Level Shifter BOB 12009
 - Why Level Shifter BOB 12009:
   - It is being added to the project to ensure that
blocks like beagle bone and finger print module working
at different voltages will operate correctly when
integrated together.
- [ ] Storage Media
 - Why Storage Media:
   - a particular storage media will be taken
here where data will be stored. This media can be
a pen drive or hard disk.
- [ ] Keypad Butons
 - Why Keypad:
   - This will be introduced in the project by using two
buttons for putting in the password.
