### ISSUE TITLE
Install all the required software

### ISSUE THREAD

**Issue by mikeshams** [srikanthpendem/capstoneproject#6]

**Comment by mikeshams** [comment]
Demonstrate how to encrypt and decrypt a pen drive using LUKS

**Comment by mikeshams** [comment]
1. What issues did you or others might face with installing different Software you need?

**Comment by Devanggajjar** [comment]
Issues which we are facing are as follow:
1.) Connect BBB with WIFI using a hotspot of mobile phones especially "**Iphones**". But we are trying to get rid of that issue too.
2.) Also to connect the project with the cloud service AWS we are facing the problem, but soon we will find the solution.
