### ISSUE TITLE
Connect WiFi to BBB/ Establish Internet connection to the project

### ISSUE THREAD

**Issue by srikanthpendem** [srikanthpendem/capstoneproject#9]

**Comment by loveuppal** [comment]
**Intsructions** **to** **connect Wi-Fi to BBB.**

Note: You will need Internet connection to get through these steps. Please refer Share WiFi over Ethernet on this same directory.

- Initially check if you have already installed a Wi-Fi driver in your BBB. (probably it is not.)

- Open terminal and type iwconfig to check if you can see wlan0.

- If you dont have one, it does mean you've no Wi-Fi driver installed.

- Check online if the Wi-Fi adapter you are using has drivers for linux.

- T2U Nano Wi-fi adpater driver Installation.

- Connect ethernet to your BBB to access the internet.


Download the latest kernel-headers of your BBB.
$ **sudo apt install linux-headers-$(uname -r)**

Update and Upgrade you BBB.
$ **sudo apt update && sudo apt upgrade****

Do as follows
   **$ sudo apt install dkms
   $ git clone -b v5.6.4.2 https://github.com/aircrack-ng/rtl8812au.git
   $ cd rtl8812au
   $ sudo ./dkms-install.sh  >>usually takes a long time to complete, be patient.
   $ sudo reboot**

- After reboot, SSH to you BBB.

- Open terminal and type iwconfig to check if you can see wlan0.

- if yes, you've successfully installed the drives Cheers!

- Connect BBB to a Wi-Fi nearby network

Do as follows
**$ connmanctl> agent on
Agent Registerd.

$ connmanctl> scan wifi
Scan completed for wifi.
sudo connmanctl (this is already installed in your BBB)

$ connmanctl> services
You will see a list of available Wi-Fi nearby with their SSID name and its ID tag.

$ connmanctl> connect wifi_d066842gfjfk_48545erfd_managed_psk******

Passphrase? •••••••• type the password</br>
connected wifi_d066842gfjfk_48545erfd_managed_psk
You've successfully connected ping 8.8.8.8 to check the connection

**Comment by mikeshams** [comment]
**Demonstrate connectivity with hotspot if thee is no wifi**

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of wifi module to the BBB in terms of Hardware and Software?
2. What will you do if there is no wifi and you have only Data on your cell phone?

**Comment by loveuppal** [comment]
Ques- 1. What issues did you or others might face with connection of wifi module to the BBB in terms of Hardware and Software?

1.If the BBB has no installed driveres, WiFi might not work.
2. Make sure that the wifi adapter we buy has driver support on all the platforms.
3. If wifi adapter doesnt able to draw 3.3V from USB, the wifi may not work properly. we have to use external power source like USB Hubs.

Ques 2.-What will you do if there is no wifi and you have only Data on your cell phone?
1. The BBB Linux is not supporting the iphone's wifi hotspot. I think this is a bug either from OS or the wifi driver.
2. We have to connect to either a router or anyother andriod phone's hotspot.
